/**
 * Macro-categorie per i filtri in Gestisci progetti.
 * Mappatura project id → macro categoria.
 */
export const MACRO_CATEGORIES = [
  { id: "all", label: "Tutti" },
  { id: "blockchain", label: "Blockchain" },
  { id: "portafogli", label: "Portafogli" },
  { id: "compra-vendi-crypto", label: "Compra/Vendi Crypto" },
  { id: "defi", label: "DeFi" },
  { id: "airdrops", label: "Airdrops" },
  { id: "memecoin", label: "Memecoin" },
  { id: "nft", label: "NFT" },
  { id: "strumenti-utili", label: "Strumenti utili" },
  { id: "giochi-metaversi", label: "Giochi / Metaversi" },
  { id: "other", label: "Altro" },
] as const;

export type MacroCategoryId = (typeof MACRO_CATEGORIES)[number]["id"];

/** Project id (lowercase) → macro category */
export const PROJECT_MACRO_CATEGORY: Record<string, MacroCategoryId> = {
  // Blockchain
  bitcoin: "blockchain",
  ethereum: "blockchain",
  solana: "blockchain",
  base: "blockchain",
  arbitrum: "blockchain",
  optimism: "blockchain",
  polygon: "blockchain",
  "polygon-zkevm": "blockchain",
  polygon_zkevm: "blockchain",
  avalanche: "blockchain",
  scroll: "blockchain",
  zksync: "blockchain",
  linea: "blockchain",
  blast: "blockchain",
  berachain: "blockchain",
  hyperlane: "blockchain",
  layer3: "blockchain",
  zora: "blockchain",
  hyperevm: "blockchain",
  "sonic-rename": "blockchain",
  abstract: "blockchain",
  extended: "blockchain",
  // Portafogli
  metamask: "portafogli",
  phantom: "portafogli",
  rabby: "portafogli",
  rainbow: "portafogli",
  ledger: "portafogli",
  trezor: "portafogli",
  safe: "portafogli",
  // Compra/Vendi Crypto
  coinbase: "compra-vendi-crypto",
  kraken: "compra-vendi-crypto",
  binance: "compra-vendi-crypto",
  holyheld: "compra-vendi-crypto",
  transak: "compra-vendi-crypto",
  "crypto-com": "compra-vendi-crypto",
  wirex: "compra-vendi-crypto",
  "young-platform": "compra-vendi-crypto",
  // DeFi
  uniswap: "defi",
  aave: "defi",
  curve: "defi",
  compound: "defi",
  balancer: "defi",
  hyperliquid: "defi",
  jumper: "defi",
  debridge: "defi",
  stargate: "defi",
  orbiter: "defi",
  jupiter: "defi",
  raydium: "defi",
  camelot: "defi",
  "cow-swap": "defi",
  liquity: "defi",
  moonwell: "defi",
  tapioca: "defi",
  marginfi: "defi",
  kamino: "defi",
  "lido-finance": "defi",
  "yearn-finance": "defi",
  hyperlend: "defi",
  hypurrfi: "defi",
  syncswap: "defi",
  layerzero: "defi",
  "relay-bridge": "defi",
  "propellerswap": "defi",
  cielo: "defi",
  limitless: "defi",
  lighter: "defi",
  felix: "defi",
  rysk: "defi",
  mirror: "defi",
  "trader-joe": "defi",
  llamaswap: "defi",
  ostium: "defi",
  pacifica: "defi",
  smilee: "defi",
  variational: "defi",
  "the-honey-jar": "defi",
  usdc: "defi",
  usdt: "defi",
  bunni: "defi",
  hibachi: "defi",
  ink: "blockchain",
  "drip-trade": "defi",
  // Airdrops / tools
  getgrass: "airdrops",
  gitcoin: "airdrops",
  snapshot: "airdrops",
  ens: "airdrops",
  farcaster: "airdrops",
  // Memecoin
  dogecoin: "memecoin",
  "pepe-coin": "memecoin",
  apu: "memecoin",
  degen: "memecoin",
  higher: "memecoin",
  "dogwifhat-wif": "memecoin",
  boden: "memecoin",
  kenidy: "memecoin",
  retardio: "memecoin",
  floppa: "memecoin",
  "shark-cat": "memecoin",
  tremp: "memecoin",
  bonk: "memecoin",
  // NFT
  opensea: "nft",
  blur: "nft",
  sudoswap: "nft",
  "crypto-punks": "nft",
  "pudgy-penguins": "nft",
  milady: "nft",
  "tubby-cats": "nft",
  radbro: "nft",
  shroomiez: "nft",
  "bong-bears-and-rebase": "nft",
  "redacted-remilio-babies": "nft",
  "fractional-uprising-fu": "nft",
  polymarket: "nft",
  // Strumenti utili
  coingecko: "strumenti-utili",
  dexscreener: "strumenti-utili",
  defillama: "strumenti-utili",
  "token-terminal": "strumenti-utili",
  debank: "strumenti-utili",
  nansen: "strumenti-utili",
  defined: "strumenti-utili",
  zapper: "strumenti-utili",
  zerion: "strumenti-utili",
  "gas-zip": "strumenti-utili",
  "token-unlocks": "strumenti-utili",
  "core-explorer-allbridge": "strumenti-utili",
  socketscan: "strumenti-utili",
  "symbiosis-explorer": "strumenti-utili",
  symbiosis: "strumenti-utili",
  "smol-refuel": "strumenti-utili",
  coinglass: "strumenti-utili",
  chainlink: "strumenti-utili",
  // Giochi / Metaversi
  decentraland: "giochi-metaversi",
  "the-sandbox": "giochi-metaversi",
  "nifty-island": "giochi-metaversi",
  treasure: "giochi-metaversi",
  ohbabygames: "giochi-metaversi",
  truemarkets: "giochi-metaversi",
  "tn100x-ham-thelp": "giochi-metaversi",
};

export function getProjectMacroCategory(projectId: string): MacroCategoryId {
  return PROJECT_MACRO_CATEGORY[projectId.toLowerCase()] ?? "other";
}
