/**
 * Progetti estratti dal database Notion ImparoDeFi (export 6 marzo).
 * Solo progetti con almeno Sito Web e Profilo Twitter/X.
 * Fonte: imparodefi-ita-6march-export.zip
 */
export const NOTION_CATALOG_PROJECTS: {
  id: string;
  name: string;
  websiteUrl: string;
  twitterUrl: string;
  description?: string;
  category?: string;
}[] = [
  { id: 'aave', name: 'AAVE', websiteUrl: 'https://app.aave.com/', twitterUrl: 'https://x.com/aave' },
  { id: 'abstract', name: 'Abstract', websiteUrl: 'https://www.abs.xyz/', twitterUrl: 'https://x.com/AbstractChain' },
  { id: 'apu', name: 'Apu', websiteUrl: 'https://apu.com/', twitterUrl: 'https://x.com/ApusCoin' },
  { id: 'arbitrum', name: 'Arbitrum', websiteUrl: 'https://arbitrum.foundation/', twitterUrl: 'https://x.com/arbitrum' },
  { id: 'avalanche', name: 'Avalanche', websiteUrl: 'https://www.avax.network/', twitterUrl: 'https://x.com/avax' },
  { id: 'balancer', name: 'Balancer', websiteUrl: 'https://balancer.fi/', twitterUrl: 'https://x.com/Balancer' },
  { id: 'base', name: 'Base', websiteUrl: 'https://www.base.org/', twitterUrl: 'https://x.com/base' },
  { id: 'berachain', name: 'Berachain', websiteUrl: 'https://www.berachain.com/', twitterUrl: 'https://x.com/berachain' },
  { id: 'binance', name: 'Binance', websiteUrl: 'https://www.binance.com', twitterUrl: 'https://x.com/binance' },
  { id: 'bitcoin', name: 'Bitcoin', websiteUrl: 'https://bitcoin.org/bitcoin.pdf', twitterUrl: 'https://x.com/bitcoin' },
  { id: 'blast', name: 'Blast', websiteUrl: 'https://blast.io', twitterUrl: 'https://x.com/Blast_L2' },
  { id: 'blur', name: 'Blur', websiteUrl: 'https://blur.io/', twitterUrl: 'https://x.com/blur_io' },
  { id: 'boden', name: 'Boden', websiteUrl: 'https://boden4pres.com', twitterUrl: 'https://x.com/boden4pres' },
  { id: 'bong-bears-and-rebase', name: 'Bong Bears & Rebase', websiteUrl: 'https://www.berachain.com/', twitterUrl: 'https://x.com/BongBearsNFT' },
  { id: 'camelot', name: 'Camelot', websiteUrl: 'https://app.camelot.exchange/', twitterUrl: 'https://x.com/CamelotDEX' },
  { id: 'chainlink', name: 'Chainlink', websiteUrl: 'https://chain.link/', twitterUrl: 'https://x.com/chainlink' },
  { id: 'cielo', name: 'Cielo', websiteUrl: 'https://cielo.finance/', twitterUrl: 'https://x.com/cielofinance' },
  { id: 'coinbase', name: 'Coinbase', websiteUrl: 'https://www.coinbase.com/', twitterUrl: 'https://twitter.com/coinbase' },
  { id: 'coingecko', name: 'Coingecko', websiteUrl: 'https://coingecko.com', twitterUrl: 'https://x.com/coingecko' },
  { id: 'compound', name: 'Compound', websiteUrl: 'https://compound.finance/', twitterUrl: 'https://x.com/compoundfinance' },
  { id: 'core-explorer-allbridge', name: 'Core Explorer (allbridge)', websiteUrl: 'https://core.allbridge.io/explorer', twitterUrl: 'https://x.com/Allbridge_io' },
  { id: 'cow-swap', name: 'Cow Swap', websiteUrl: 'https://cow.fi/', twitterUrl: 'https://x.com/CoWSwap' },
  { id: 'crypto-com', name: 'Crypto com', websiteUrl: 'https://crypto.com/', twitterUrl: 'https://x.com/cryptocom' },
  { id: 'crypto-punks', name: 'Crypto Punks', websiteUrl: 'https://cryptopunks.app/', twitterUrl: 'https://x.com/cryptopunksnfts' },
  { id: 'curve', name: 'Curve', websiteUrl: 'https://curve.fi/', twitterUrl: 'https://x.com/CurveFinance' },
  { id: 'debank', name: 'DeBank', websiteUrl: 'https://DeBank.com', twitterUrl: 'https://x.com/DeBankDeFi' },
  { id: 'debridge', name: 'deBridge', websiteUrl: 'https://debridge.finance/', twitterUrl: 'https://x.com/deBridgeFinance' },
  { id: 'decentraland', name: 'Decentraland', websiteUrl: 'https://decentraland.org/', twitterUrl: 'https://x.com/decentraland' },
  { id: 'defillama', name: 'Defillama', websiteUrl: 'https://defillama.com/', twitterUrl: 'https://x.com/DefiLlama' },
  { id: 'defined', name: 'Defined', websiteUrl: 'https://www.defined.fi/', twitterUrl: 'https://x.com/definedfi' },
  { id: 'degen', name: 'Degen', websiteUrl: 'https://degen.tips', twitterUrl: 'https://x.com/degentokenbase' },
  { id: 'derive', name: 'Derive', websiteUrl: 'https://www.derive.xyz', twitterUrl: 'https://x.com/derivexyz', description: 'Piattaforma DeFi per trading di derivati on-chain con focus su perpetual e opzioni.' },
  { id: 'dexscreener', name: 'Dexscreener', websiteUrl: 'https://dexscreener.com', twitterUrl: 'https://x.com/dexscreener' },
  { id: 'dogecoin', name: 'Dogecoin', websiteUrl: 'https://dogecoin.com/', twitterUrl: 'https://x.com/dogecoin' },
  { id: 'dogwifhat-wif', name: 'Dogwifhat (WIF)', websiteUrl: 'https://Dogwifcoin.org', twitterUrl: 'https://x.com/dogwifcoin' },
  { id: 'drip-trade', name: 'Drip trade', websiteUrl: 'https://drip.trade', twitterUrl: 'https://x.com/drip__trade' },
  { id: 'ens', name: 'ENS', websiteUrl: 'https://ens.domains/', twitterUrl: 'https://x.com/ensdomains' },
  { id: 'ethereum', name: 'Ethereum', websiteUrl: 'https://ethereum.org/it/', twitterUrl: 'https://x.com/ethereum' },
  { id: 'extended', name: 'Extended', websiteUrl: 'https://app.extended.exchange/join/EXTEND777', twitterUrl: 'https://x.com/extendedapp' },
  { id: 'farcaster', name: 'Farcaster', websiteUrl: 'https://farcaster.xyz/', twitterUrl: 'https://twitter.com/warpcast_' },
  { id: 'felix', name: 'Felix', websiteUrl: 'https://www.usefelix.xyz?ref=EBB69FF2', twitterUrl: 'https://x.com/felixprotocol' },
  { id: 'floppa', name: 'Floppa', websiteUrl: 'https://floppa.wtf/', twitterUrl: 'https://x.com/floppa/' },
  { id: 'fractional-uprising-fu', name: 'Fractional Uprising (FU)', websiteUrl: 'https://www.fustudios.io/', twitterUrl: 'https://x.com/FU_STUDIOS' },
  { id: 'gas-zip', name: 'Gas zip', websiteUrl: 'https://www.gas.zip/', twitterUrl: 'https://x.com/gasdotzip' },
  { id: 'getgrass', name: 'Getgrass', websiteUrl: 'https://www.getgrass.io/', twitterUrl: 'https://x.com/getgrass_io' },
  { id: 'gitcoin', name: 'Gitcoin', websiteUrl: 'https://www.gitcoin.co/', twitterUrl: 'https://twitter.com/gitcoin' },
  { id: 'higher', name: 'Higher', websiteUrl: 'https://www.aimhigher.net/', twitterUrl: 'https://x.com/higheronchain' },
  { id: 'holyheld', name: 'Holyheld', websiteUrl: 'https://holyheld.com/', twitterUrl: 'https://x.com/holyheld' },
  { id: 'hyperevm', name: 'HyperEVM', websiteUrl: 'https://hyperfoundation.org/', twitterUrl: 'https://x.com/HyperliquidX' },
  { id: 'hyperlane', name: 'Hyperlane', websiteUrl: 'https://www.hyperlane.xyz/', twitterUrl: 'https://x.com/hyperlane' },
  { id: 'hyperlend', name: 'Hyperlend', websiteUrl: 'https://hyperlend.finance/', twitterUrl: 'https://x.com/hyperlendx' },
  { id: 'hyperliquid', name: 'Hyperliquid', websiteUrl: 'https://app.hyperliquid.xyz/join/HL4567', twitterUrl: 'https://twitter.com/HyperliquidX' },
  { id: 'hypurrfi', name: 'HypurrFi', websiteUrl: 'https://www.hypurr.fi/', twitterUrl: 'https://x.com/HypurrFi' },
  { id: 'ink', name: 'Ink', websiteUrl: 'https://inkonchain.com/', twitterUrl: 'https://x.com/inkonchain' },
  { id: 'jumper', name: 'Jumper', websiteUrl: 'https://jumper.exchange/', twitterUrl: 'https://x.com/JumperExchange' },
  { id: 'jupiter', name: 'Jupiter', websiteUrl: 'https://jup.ag', twitterUrl: 'https://x.com/JupiterExchange' },
  { id: 'kamino', name: 'Kamino', websiteUrl: 'https://app.kamino.finance/', twitterUrl: 'https://x.com/KaminoFinance' },
  { id: 'kast', name: 'Kast', websiteUrl: 'https://www.kast.xyz/', twitterUrl: 'https://x.com/KASTcard' },
  { id: 'kenidy', name: 'Kenidy', websiteUrl: 'https://kenidy.io', twitterUrl: 'https://x.com/kenidy_on_sol' },
  { id: 'kraken', name: 'Kraken', websiteUrl: 'https://www.kraken.com/', twitterUrl: 'https://x.com/krakenfx' },
  { id: 'layer3', name: 'Layer3', websiteUrl: 'https://layer3.xyz/', twitterUrl: 'https://x.com/layer3xyz' },
  { id: 'layerzero', name: 'LayerZero', websiteUrl: 'https://layerzero.network/', twitterUrl: 'https://x.com/LayerZero_Labs' },
  { id: 'ledger', name: 'Ledger', websiteUrl: 'https://shop.ledger.com/', twitterUrl: 'https://x.com/Ledger' },
  { id: 'lido-finance', name: 'Lido Finance', websiteUrl: 'https://lido.fi/', twitterUrl: 'https://x.com/LidoFinance' },
  { id: 'lighter', name: 'Lighter', websiteUrl: 'https://app.lighter.xyz/?referral=3SEU75MYUJ5C', twitterUrl: 'https://x.com/Lighter_xyz' },
  { id: 'limitless', name: 'Limitless', websiteUrl: 'https://limitless.exchange/advanced', twitterUrl: 'https://x.com/trylimitless' },
  { id: 'llamaswap', name: 'LlamaSwap', websiteUrl: 'https://swap.defillama.com/?chain=ethereum&from=0x0000000000000000000000000000000000000000&tab=swap', twitterUrl: 'https://x.com/DefiLlama', description: 'Aggregatore di swap multi-DEX per routing efficiente tra chain e pool diversi.' },
  { id: 'linea', name: 'Linea', websiteUrl: 'https://linea.build/', twitterUrl: 'https://x.com/LineaBuild' },
  { id: 'liquity', name: 'Liquity', websiteUrl: 'https://liquity.org', twitterUrl: 'https://x.com/LiquityProtocol' },
  { id: 'marginfi', name: 'Marginfi', websiteUrl: 'https://www.marginfi.com/', twitterUrl: 'https://x.com/marginfi' },
  { id: 'metamask', name: 'Metamask', websiteUrl: 'https://metamask.io/', twitterUrl: 'https://twitter.com/MetaMask' },
  { id: 'milady', name: 'Milady', websiteUrl: 'https://miladymaker.net/', twitterUrl: 'https://x.com/miladymaker' },
  { id: 'mirror', name: 'Mirror', websiteUrl: 'https://mirror.xyz/', twitterUrl: 'https://x.com/viamirror' },
  { id: 'moonwell', name: 'Moonwell', websiteUrl: 'https://moonwell.fi/', twitterUrl: 'https://x.com/MoonwellDeFi' },
  { id: 'nansen', name: 'Nansen', websiteUrl: 'https://www.nansen.ai/', twitterUrl: 'https://x.com/nansen_ai' },
  { id: 'nifty-island', name: 'Nifty Island', websiteUrl: 'https://niftyisland.com', twitterUrl: 'https://x.com/Nifty_Island' },
  { id: 'ohbabygames', name: 'OhBabyGames', websiteUrl: 'https://www.ohbabygames.com/', twitterUrl: 'https://x.com/OhBabyGames' },
  { id: 'opensea', name: 'OpenSea', websiteUrl: 'https://opensea.io/', twitterUrl: 'https://x.com/opensea' },
  { id: 'optimism', name: 'Optimism', websiteUrl: 'https://www.optimism.io/', twitterUrl: 'https://twitter.com/Optimism' },
  { id: 'orbiter', name: 'Orbiter', websiteUrl: 'https://www.orbiter.finance/', twitterUrl: 'https://x.com/Orbiter_Finance' },
  { id: 'ostium', name: 'Ostium', websiteUrl: 'https://app.ostium.com/trade?from=SPX&amp;to=USD&amp;ref=QR69Q', twitterUrl: 'https://x.com/OstiumLabs' },
  { id: 'pacifica', name: 'Pacifica', websiteUrl: 'https://app.pacifica.fi/', twitterUrl: 'https://x.com/pacifica_fi' },
  { id: 'pepe-coin', name: 'Pepe (coin)', websiteUrl: 'https://www.pepe.vip/', twitterUrl: 'https://x.com/pepecoineth' },
  { id: 'phantom', name: 'Phantom', websiteUrl: 'https://phantom.app/', twitterUrl: 'https://x.com/phantom' },
  { id: 'polygon', name: 'Polygon', websiteUrl: 'https://polygon.technology/', twitterUrl: 'https://x.com/0xPolygon' },
  { id: 'polygon-zkevm', name: 'Polygon zkEVM', websiteUrl: 'https://polygon.technology/', twitterUrl: 'https://x.com/0xpolygondefi' },
  { id: 'polymarket', name: 'Polymarket', websiteUrl: 'https://polymarket.com/', twitterUrl: 'https://x.com/Polymarket' },
  { id: 'propellerswap', name: 'PropellerSwap', websiteUrl: 'https://www.propellerheads.xyz/', twitterUrl: 'https://x.com/propellerswap' },
  { id: 'pudgy-penguins', name: 'Pudgy Penguins', websiteUrl: 'https://www.pudgypenguins.com/', twitterUrl: 'https://x.com/pudgypenguins' },
  { id: 'rabby', name: 'Rabby', websiteUrl: 'https://rabby.io/', twitterUrl: 'https://x.com/Rabby_io' },
  { id: 'radbro', name: 'Radbro', websiteUrl: 'https://radbro.xyz/', twitterUrl: 'https://x.com/radbro_webring' },
  { id: 'rainbow', name: 'Rainbow', websiteUrl: 'https://rainbow.me/', twitterUrl: 'https://x.com/rainbowdotme' },
  { id: 'raydium', name: 'Raydium', websiteUrl: 'https://raydium.io', twitterUrl: 'https://x.com/RaydiumProtocol' },
  { id: 'redacted-remilio-babies', name: 'Redacted Remilio Babies', websiteUrl: 'https://remilio.org/', twitterUrl: 'https://x.com/RemilioBaby' },
  { id: 'relay-bridge', name: 'Relay Bridge', websiteUrl: 'https://relay.link/', twitterUrl: 'https://x.com/RelayProtocol' },
  { id: 'retardio', name: 'Retardio', websiteUrl: 'https://retardio.xyz/', twitterUrl: 'https://x.com/retardiosolana' },
  { id: 'rysk', name: 'Rysk', websiteUrl: 'https://app.rysk.finance/', twitterUrl: 'https://x.com/ryskfinance' },
  { id: 'safe', name: 'Safe', websiteUrl: 'https://safe.global/', twitterUrl: 'https://x.com/safe' },
  { id: 'scroll', name: 'Scroll', websiteUrl: 'https://scroll.io/', twitterUrl: 'https://x.com/Scroll_ZKP' },
  { id: 'shark-cat', name: 'Shark Cat', websiteUrl: 'https://sharkcatsolana.com', twitterUrl: 'https://x.com/SharkCatSolana' },
  { id: 'shroomiez', name: 'Shroomiez', websiteUrl: 'https://shroomiez.world', twitterUrl: 'https://x.com/ShroomiezNFTs' },
  { id: 'smilee', name: 'Smilee', websiteUrl: 'https://app.smilee.finance/', twitterUrl: 'https://x.com/SmileeFinance' },
  { id: 'smol-refuel', name: 'Smol Refuel', websiteUrl: 'https://smolrefuel.com/', twitterUrl: 'https://x.com/smolrefuel' },
  { id: 'snapshot', name: 'Snapshot', websiteUrl: 'https://snapshot.org', twitterUrl: 'https://x.com/SnapshotLabs' },
  { id: 'socketscan', name: 'Socketscan', websiteUrl: 'https://www.socketscan.io/', twitterUrl: 'https://x.com/SocketDotTech' },
  { id: 'solana', name: 'Solana', websiteUrl: 'https://solana.com/', twitterUrl: 'https://x.com/solana' },
  { id: 'sonic-rename', name: 'Sonic (rename)', websiteUrl: 'https://www.soniclabs.com/', twitterUrl: 'https://x.com/FantomFDN' },
  { id: 'stargate', name: 'Stargate', websiteUrl: 'https://stargate.finance/', twitterUrl: 'https://x.com/StargateFinance' },
  { id: 'sudoswap', name: 'Sudoswap', websiteUrl: 'https://sudoswap.xyz', twitterUrl: 'https://x.com/sudoswap' },
  { id: 'symbiosis', name: 'Symbiosis', websiteUrl: 'https://app.symbiosis.finance/', twitterUrl: 'https://x.com/symbiosis_fi' },
  { id: 'symbiosis-explorer', name: 'Symbiosis Explorer', websiteUrl: 'https://explorer.symbiosis.finance/', twitterUrl: 'https://x.com/symbiosis_fi' },
  { id: 'syncswap', name: 'Syncswap', websiteUrl: 'https://syncswap.xyz/', twitterUrl: 'https://twitter.com/syncswap' },
  { id: 'tapioca', name: 'Tapioca', websiteUrl: 'https://genesis.permissionless.one/', twitterUrl: 'https://x.com/tapioca_dao' },
  { id: 'the-honey-jar', name: 'The Honey Jar', websiteUrl: 'https://hub.xyz/honeyjar', twitterUrl: 'https://x.com/0xhoneyjar' },
  { id: 'the-sandbox', name: 'The Sandbox', websiteUrl: 'https://x.com/TheSandboxGame', twitterUrl: 'https://x.com/TheSandboxGame' },
  { id: 'tn100x-ham-thelp', name: 'TN100X (Ham TheLP)', websiteUrl: 'https://ham.fun/', twitterUrl: 'https://x.com/HamOnWarpcast' },
  { id: 'token-terminal', name: 'Token Terminal', websiteUrl: 'https://tokenterminal.com/', twitterUrl: 'https://x.com/tokenterminal' },
  { id: 'token-unlocks', name: 'Token Unlocks', websiteUrl: 'https://token.unlocks.app/', twitterUrl: 'https://x.com/Token_Unlocks' },
  { id: 'tokenomist', name: 'Tokenomist', websiteUrl: 'https://tokenomist.ai/', twitterUrl: 'https://x.com/Tokenomist_ai' },
  { id: 'trader-joe', name: 'Trader Joe', websiteUrl: 'https://lfj.gg/avalanche', twitterUrl: 'https://x.com/traderjoe_xyz' },
  { id: 'transak', name: 'Transak', websiteUrl: 'https://transak.com/', twitterUrl: 'https://twitter.com/Transak' },
  { id: 'treasure', name: 'Treasure', websiteUrl: 'https://treasure.lol/', twitterUrl: 'https://x.com/Treasure_DAO' },
  { id: 'tremp', name: 'Tremp', websiteUrl: 'https://tremp.xyz', twitterUrl: 'https://x.com/dolandtremp_sol' },
  { id: 'trezor', name: 'Trezor', websiteUrl: 'https://trezor.io/', twitterUrl: 'https://x.com/Trezor' },
  { id: 'truemarkets', name: 'Truemarkets', websiteUrl: 'https://truemarkets.org/', twitterUrl: 'https://x.com/truemarkets' },
  { id: 'tubby-cats', name: 'Tubby Cats', websiteUrl: 'https://hub.xyz/tubby-cats', twitterUrl: 'https://x.com/tubbycatsnft' },
  { id: 'uniswap', name: 'Uniswap', websiteUrl: 'https://app.uniswap.org/swap', twitterUrl: 'https://x.com/Uniswap' },
  { id: 'usdc', name: 'USDC', websiteUrl: 'https://www.circle.com/usdc', twitterUrl: 'https://x.com/circle', description: 'Stablecoin fiat-collateralizzata usata per pagamenti e operativita DeFi.' },
  { id: 'usdt', name: 'USDT', websiteUrl: 'https://tether.to/', twitterUrl: 'https://x.com/Tether_to', description: 'Stablecoin ancorata al dollaro con alta liquidita su exchange e protocolli.' },
  { id: 'variational', name: 'Variational', websiteUrl: 'https://omni.variational.io/?ref=OMNIFALS5KIJ', twitterUrl: 'https://x.com/variational_io' },
  { id: 'wirex', name: 'Wirex', websiteUrl: 'https://wirexapp.com/', twitterUrl: 'https://x.com/wirexapp' },
  { id: 'yearn-finance', name: 'Yearn Finance', websiteUrl: 'https://yearn.fi/', twitterUrl: 'https://x.com/yearnfi' },
  { id: 'young-platform', name: 'Young Platform', websiteUrl: 'https://exchange.youngplatform.com/', twitterUrl: 'https://x.com/youngplatform' },
  { id: 'zapper', name: 'Zapper', websiteUrl: 'https://zapper.xyz/', twitterUrl: 'https://x.com/zapper_fi' },
  { id: 'zerion', name: 'Zerion', websiteUrl: 'https://zerion.io/', twitterUrl: 'https://x.com/zerion' },
  { id: 'zksync', name: 'zkSync', websiteUrl: 'https://zksync.io/', twitterUrl: 'https://x.com/zksync' },
  { id: 'zora', name: 'Zora', websiteUrl: 'https://zora.co/', twitterUrl: 'https://x.com/ourZORA' },
];