/**
 * Mappa projectId (slug piattaforma) -> CoinGecko coin id per progetti con token live.
 * Usata per mostrare prezzo e market cap nella pagina Esplora l'Ecosistema.
 */
export const PROJECT_COINGECKO_IDS: Record<string, string> = {
  bitcoin: "bitcoin",
  ethereum: "ethereum",
  solana: "solana",
  arbitrum: "arbitrum",
  optimism: "optimism",
  polygon: "polygon-ecosystem-token",
  avalanche: "avalanche-2",
  base: "base-2",
  scroll: "scroll",
  zksync: "zksync",
  linea: "linea",
  blast: "blast",
  berachain: "berachain-berachain",
  fantom: "fantom",
  bsc: "binancecoin",
  cosmos: "cosmos",
  gnosis: "gnosis",
  xai: "xai-blockchain",
  hyperliquid: "hyperliquid",
  aave: "aave",
  compound: "compound-governance-token",
  curve: "curve-dao-token",
  balancer: "balancer",
  uniswap: "uniswap",
  "1inch": "1inch",
  "lido-finance": "lido-dao",
  "yearn-finance": "yearn-finance",
  jupiter: "jupiter-exchange-solana",
  raydium: "raydium",
  stargate: "stargate-finance",
  layerzero: "layer-zero",
  syncswap: "syncswap",
  camelot: "camelot-token",
  debridge: "debridge",
  chainlink: "chainlink",
  dogecoin: "dogecoin",
  "pepe-coin": "pepe",
  "dogwifhat-wif": "dogwifcoin",
  apu: "apu-apustaja",
  degen: "degen-base",
  boden: "joe-biden",
  floppa: "floppa",
  higher: "higher",
  ink: "ink",
  ens: "ethereum-name-service",
  gitcoin: "gitcoin",
  zora: "zora",
  opensea: "opensea",
  blur: "blur",
  "the-sandbox": "sandbox",
  decentraland: "decentraland",
  polymarket: "polymarket",
  "trader-joe": "joe",
  "magic-eden": "magic-eden",
  treasure: "treasure",
  radbro: "radbro",
  "propellerswap": "propeller",
  safe: "safe",
  liquity: "liquity",
  moonwell: "moonwell",
  kamino: "kamino-finance",
  abstract: "abstract",
  usdc: "usd-coin",
  usdt: "tether",
};

export function getCoingeckoId(projectId: string): string | null {
  return PROJECT_COINGECKO_IDS[projectId.toLowerCase()] ?? null;
}
