import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Navbar } from "@/components/Navbar";
import { Overpass, Roboto, Oxygen_Mono } from "next/font/google";

const overpass = Overpass({
  variable: "--font-overpass",
  display: "swap",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});
const oxygen = Oxygen_Mono({
  variable: "--font-oxygen",
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overpass.variable} ${roboto.variable} ${oxygen.variable} antialiased font-overpass bg-background`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
