import type { Metadata } from "next";
import "./globals.css";
// import "bootstrap/dist/css/bootstrap.min.css";
import { Navbar } from "@/components/Navbar";
import { Overpass, Roboto, Oxygen_Mono } from "next/font/google";
import { Footer } from "@/components/Footer";

const overpass = Overpass({
  variable: "--font-overpass",
  display: "swap",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  display: "swap",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});
const oxygen = Oxygen_Mono({
  variable: "--font-oxygen",
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overpass.variable} ${roboto.variable} ${oxygen.variable} text-black antialiased font-overpass bg-background flex flex-col items-center`}
      >
        <Navbar />
        <div className="w-full max-w-screen-2xl px-4 min-h-lvh">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
